# Generated by Django 5.0 on 2024-01-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="jacket_men",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jacket_men", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="jacket_women",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jacket_women", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="jeans_men",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jeans_men", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="jeans_women",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jeans_women", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="shirts_men",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shirt_men", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="shirts_women",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shirt_women", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="shoes_men",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shoes_company", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="shoes_women",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shoes_company", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tshirt_men",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tshirt_men", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tshirt_women",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tshirt_women", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="jacket_men_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("man_sopic", models.ImageField(upload_to="womenshoes")),
                ("man_so_discprtion", models.CharField(max_length=50)),
                ("man_soprise", models.IntegerField()),
                (
                    "man_fks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apk.jacket_men"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="jacket_women_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("woman_sopic", models.ImageField(upload_to="womenshoes")),
                ("woman_so_discprtion", models.CharField(max_length=50)),
                ("woman_soprise", models.IntegerField()),
                (
                    "woman_fks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apk.jacket_women",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="jeans_men_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("man_sopic", models.ImageField(upload_to="womenshoes")),
                ("man_so_discprtion", models.CharField(max_length=50)),
                ("man_soprise", models.IntegerField()),
                (
                    "man_fks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apk.jeans_men"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="jeans_women_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("woman_sopic", models.ImageField(upload_to="womenshoes")),
                ("woman_so_discprtion", models.CharField(max_length=50)),
                ("woman_soprise", models.IntegerField()),
                (
                    "woman_fks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apk.jeans_women",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="shirts_men_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("man_sopic", models.ImageField(upload_to="womenshoes")),
                ("man_so_discprtion", models.CharField(max_length=50)),
                ("man_soprise", models.IntegerField()),
                (
                    "man_fks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apk.shirts_men"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="shirts_women_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("woman_sopic", models.ImageField(upload_to="womenshoes")),
                ("woman_so_discprtion", models.CharField(max_length=50)),
                ("woman_soprise", models.IntegerField()),
                (
                    "woman_fks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apk.shirts_women",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="man_shoe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("man_sopic", models.ImageField(upload_to="menshoes")),
                ("man_so_discprtion", models.CharField(max_length=50)),
                ("man_soprise", models.IntegerField()),
                (
                    "man_fks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apk.shoes_men"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tshirt_men_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("man_sopic", models.ImageField(upload_to="womenshoes")),
                ("man_so_discprtion", models.CharField(max_length=50)),
                ("man_soprise", models.IntegerField()),
                (
                    "man_fks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apk.tshirt_men"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tshirts_women_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("woman_sopic", models.ImageField(upload_to="womenshoes")),
                ("woman_so_discprtion", models.CharField(max_length=50)),
                ("woman_soprise", models.IntegerField()),
                (
                    "woman_fks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apk.tshirt_women",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="woman_shoe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("woman_sopic", models.ImageField(upload_to="womenshoes")),
                ("woman_so_discprtion", models.CharField(max_length=50)),
                ("woman_soprise", models.IntegerField()),
                (
                    "woman_fks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apk.shoes_women",
                    ),
                ),
            ],
        ),
    ]
