# Generated by Django 5.0 on 2024-01-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jacket_men_data",
            name="man_sopic",
            field=models.ImageField(upload_to="jackets_men"),
        ),
        migrations.AlterField(
            model_name="jacket_women_data",
            name="woman_sopic",
            field=models.ImageField(upload_to="jacket_women"),
        ),
        migrations.AlterField(
            model_name="jeans_men_data",
            name="man_sopic",
            field=models.ImageField(upload_to="jeans_men"),
        ),
        migrations.AlterField(
            model_name="jeans_women_data",
            name="woman_sopic",
            field=models.ImageField(upload_to="jeans_women"),
        ),
        migrations.AlterField(
            model_name="shirts_men_data",
            name="man_sopic",
            field=models.ImageField(upload_to="Shirts_men"),
        ),
        migrations.AlterField(
            model_name="shirts_women_data",
            name="woman_sopic",
            field=models.ImageField(upload_to="shirts_women"),
        ),
        migrations.AlterField(
            model_name="tshirt_men_data",
            name="man_sopic",
            field=models.ImageField(upload_to="Tshirts_men"),
        ),
        migrations.AlterField(
            model_name="tshirts_women_data",
            name="woman_sopic",
            field=models.ImageField(upload_to="Tshirts_womens"),
        ),
    ]
